plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - jekyll-remote-theme
remote_theme: benbalter/retlab@v1.0.0 

title: HeringtonPress

//pages-themes/slate@v0.2.0
//benbalter/retlab@v1.0.0 
